version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200

#  logstash:
#    container_name: logstash
#    image: docker.elastic.co/logstash/logstash:7.11.0
#    volumes:
#      #- /logstash/config/:/usr/share/logstash/config:ro,Z
#      - ~/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
#      - ~/logstash/data:/usr/share/logstash/data:ro,Z
#    ports:
#      - "5044:5044"
#      - "50000:50000/tcp"
#      - "50000:50000/udp"
#      - "9600:9600"
#    environment:
#      LS_JAVA_OPTS: -Xms256m -Xmx256m
#
#    networks:
#      - es-net
#    depends_on:
#      - elasticsearch

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge